config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :authors
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :author
	has_one_attached :avatar
	attr_accessor :avatar, :file
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :articles
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name,:description,:author_id,:author_name,:avatar)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:author_name,:email,:image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index 
	end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/articles/_form.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: black">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class='form-group'>
    <%= form.label :name,class:'form-label mb-2 mt-3' %>
    <%= form.text_field :name, class:'form-control form-control-lg' %>
  </div>

  <div class='form-group'>
    <%= form.label :description, class:'form-label mb-2 mt-3',rows:'4',cols:'50' %>
    <%= form.text_area :description, class:'form-control form-control-lg' %>
  </div>

  <div class='form-group'>
    <%= form.label :avatar, class:'form-label mb-2 mt-3',rows:'4',cols:'50' %>
    <%= form.file_field :avatar, class:'form-control form-control-lg' %>
  </div>


  <div class='form-group'>
    <%= form.label :author_name, class:'form-label mb-2 mt-3' %>
    <%= form.text_field :author_name, class:'form-control form-control-lg'%>
  </div>
   <div class='form-group'>
    <%= form.label :author_id, class:'form-label mb-2 mt-3' %>
    <%= form.number_field :author_id, class:'form-control form-control-lg'%>
  </div>

  <br>

  <div>
    <%= form.submit class: "btn btn-primary"%>
    <%= link_to 'Back', articles_path, class: "btn btn-secondary"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class='container'>
  <h1><%=@article.name%></h1>
  <%= render "form", article: @article %>

  <br>
</div>

app/views/articles/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <div class='container'> 
      <br><br>
      <h1>Articles</h1>
      <br>
      <div>
        <%= link_to 'Create New', new_article_path, class: 'btn btn-primary' %>
      </div>
      <br>
      <table>
        <thead>
          <table class="w3-table-all">
          <tr class="w3-light-grey w3-hover-grey">
            <th>Name</th>
            <th>Description</th>
            <th>Author</th>
            <th colspan = '3'>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr class="w3-hover-grey">
            <td> <%= article.name %> </td>
            <td> <%= article.description%> </td>
            <td> <%= article.author_name %> </td>
            <td><%= link_to 'View',article_url(article), class: 'btn btn-light'%></td>  
            <td><%= link_to 'Delete',article_url(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
</div>

app/views/articles/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="container">

<h1>New Article</h1>


<%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="container">

  <br><br>

  <h1><%= @article.name%></h1>
  <p>Author: <b><%= @article.author_name%></b></p>
  <div class="card" style="width: 80rem; font-size: 20px;">
  <%= image_tag("Test/image.png", class:"img-fluid")%>
  <div class="card-body">
    <%= @article.description %><p>
    <%= @article.description %>
    <%= @article.description %>
    <%= @article.description %>

    <br><br>

    <%= link_to "Back", articles_path(@articles), class: 'btn btn-primary'%>
    <td><%= link_to 'Edit', edit_article_url(@article), class: 'btn btn-warning'%></td>
  </div>
</div>

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
</div>

app/views/authors/_form.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: black">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class='form-group'>
    <%= form.label :author_name,class:'form-label mb-2 mt-3' %>
    <%= form.text_field :author_name, class:'form-control form-control-lg' %>
  </div>

  <div class='form-group'>
    <%= form.label :email, class:'form-label mb-2 mt-3',rows:'4',cols:'50' %>
    <%= form.text_field :email, class:'form-control form-control-lg' %>
  </div>

  <div class='form-group'>
    <%= form.label :image, class:'form-label mb-2 mt-3',rows:'4',cols:'50' %>
    <%= form.file_field :image, class:'form-control form-control-lg' %>
  </div>
  <br>

  <div>
    <%= form.submit class: "btn btn-primary"%>
    <%= link_to 'Back', authors_path, class: "btn btn-secondary"%>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="container">
  <h1>Editing author</h1>

  <%= render "form", author: @author %>
</div>

app/views/authors/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <div class='container'> 
      <br><br>
      <h1>Authors</h1>
      <br>
      <div>
        <%= link_to 'Create New', new_author_path, class: 'btn btn-primary' %>
      </div>
      <br>
      <table>
        <thead>
          <table class="w3-table-all">
          <tr class="w3-light-grey w3-hover-grey">
            <th>Name</th>
            <th>Email</th>
            <th colspan = '3'>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @authors.each do |author| %>
            <tr class="w3-hover-grey">
            <td> <%= author.author_name %> </td>
            <td> <%= author.email%> </td>
            <td><%= link_to 'View',author_url(author), class: 'btn btn-light'%></td>  
            <td><%= link_to 'Delete',author_url(author), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
</div>

app/views/authors/new.html.erb
<div class='container'>
  <h1>New author</h1>

  <%= render "form", author: @author %>
</div>

app/views/authors/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="container-sm">
  <br><br>
  <h1><%= @author.author_name%></h1>
  <p>Name: <b><%= @author.author_name%></b></p>
  <div class="card" style="width: 80rem; font-size: 20px;">
  <%= image_tag("Test/image.png", class:"img-fluid")%>
  <div class="card-body">
    <%= @author.email%><p>

    <br><br>

    <%= link_to "Back", authors_path(@authors), class: 'btn btn-primary'%>
    <td><%= link_to 'Edit', edit_author_url(@author), class: 'btn btn-warning'%></td>
  </div>
</div>

app/views/homes/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="container-sm">

        <br><br><br><br><br><br>

        <div class="jumbotron">
            <h1 class="display-4">Programmers Nest</h1>

            <br><br>


            <p class="lead">Welcome to the programmers nest. You'll find everthing about latest programming practices here</p>
            <hr class="my-4">
            <p>Stay tuned! We are coming soon</p>
            <a class="btn btn-primary btn-lg" href="#" role="button">Sign In</a>
       </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="mystyle.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
          <nav class="navbar navbar-light bg-light">
            <div class="container">
              <a class="navbar-brand" href="#">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ruby_On_Rails_Logo.svg/1200px-Ruby_On_Rails_Logo.svg.png" alt="Logo" width="100" height="20">
              </a>
            </div>
          </nav>
        <a class="navbar-brand" href="#">Programmers Nest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="http://localhost:3000/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/articles">Articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/authors">Authors</a>
            <li class="nav-item">
              <a class="nav-link" href="#" tabindex="-1" aria-current="true">Login</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div
      class="bg-image"style="background-image: url('https://img.freepik.com/premium-photo/smooth-empty-grey-studio-well-use-as-background_1258-3149.jpg?w=2000');height: 120vh;"> 
      <%=yield%>
    </div>
    
  </body>
</html>